spring:
  # 配置SpringMVC文件上传限制，默认1M。注意MB要大写，不然报错。SpringBoot版本不同，配置项不同
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  # 配置数据源信息
  datasource:
    #配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    #配置连接数据库的各个信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.55.232.24:3306/mandarin_mate?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: liujiaxin
    password: 200212

# 配置端口
server:
  port: 9001

# 配置MyBatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 配置swagger文档的访问路径，访问地址：http://127.0.0.1:8080/swagger-ui.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Logger Config
logging:
  level:
    com:
      mandrain_mate:
        mapper: debug
        service: info
        controller: info
#        jwt相关配置
jwt:
  token:
    token-expiration: 7200000
    token-sign-key: mandrainmate
#文件上传路径
prop:
#  linux:/opt/java/mandarin_mate/
  upload-folder: E:/code/javaweb/xios/userHeadImg/

mandarin-mate:
  wechat:
    appid: wx5ce777823e868fb4
    secret: e9ef6cccd4b59e9614f0a7c50b5c3b90

alioss:
  endpoint: oss-cn-beijing.aliyuncs.com
  access-key-id: LTAI5tE5WKwASov6AE1i3xoy
  access-key-secret: DopouX54emaZ3fsehnQgXsovKUOLbR
  bucket-name: sky-take-out-keepl

